"""Operator CLI: install / uninstall / status / test.

Commands:
  jarvis-cli install     - write config, hook into ~/.claude/settings.json, install plist
  jarvis-cli uninstall   - reverse install steps (keeps user data)
  jarvis-cli status      - check daemon health
  jarvis-cli test        - send a synthetic event to the daemon
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

import httpx

import re

from .config import DEFAULT_CONFIG_PATH, expanduser, load_config

PLIST_LABEL = "com.jobin.jarvis-cli"
PLIST_PATH = expanduser(f"~/Library/LaunchAgents/{PLIST_LABEL}.plist")
CLAUDE_SETTINGS_PATH = expanduser("~/.claude/settings.json")
CODEX_CONFIG_PATH = expanduser("~/.codex/config.toml")
JARVIS_DIR = expanduser("~/.jarvis-cli")

# Sentinel comments wrap the block we own inside ~/.codex/config.toml so
# successive installs can find and replace the block without disturbing
# anything the user has hand-edited around it.
_CODEX_BLOCK_START = "# === jarvis-cli:start ==="
_CODEX_BLOCK_END = "# === jarvis-cli:end ==="
_CODEX_BLOCK_RE = re.compile(
    re.escape(_CODEX_BLOCK_START) + r".*?" + re.escape(_CODEX_BLOCK_END) + r"\n?",
    re.DOTALL,
)


def _is_our_hook(hook: dict) -> bool:
    """Match any entry whose command basename is jarvis-cli-hook (legacy bare
    name or absolute path from a previous install in a different venv)."""
    return Path(hook.get("command", "")).name == "jarvis-cli-hook"


_OUR_HOOK_TYPES = (
    "Notification",
    "UserPromptSubmit",
    "PostToolUse",
    "PostToolUseFailure",
    "SessionStart",
    "Stop",
)


def merge_claude_settings(existing: dict, hook_command: str) -> dict:
    """Install our hook entries into Notification, UserPromptSubmit, and
    PostToolUse, replacing any prior jarvis-cli-hook entries in those buckets.
    """
    out = copy.deepcopy(existing)
    hooks = out.setdefault("hooks", {})
    for hook_type in _OUR_HOOK_TYPES:
        entries = hooks.setdefault(hook_type, [])
        pruned: list[dict] = []
        for matcher in entries:
            kept = [h for h in matcher.get("hooks", []) if not _is_our_hook(h)]
            if kept:
                pruned.append({**matcher, "hooks": kept})
        pruned.append(
            {"matcher": "", "hooks": [{"type": "command", "command": hook_command}]}
        )
        out["hooks"][hook_type] = pruned
    return out


def remove_from_claude_settings(existing: dict, hook_command: str) -> dict:
    """Strip our jarvis-cli-hook entries from every hook bucket we install into.

    `hook_command` is accepted for signature compat; matching is by basename.
    """
    out = copy.deepcopy(existing)
    hooks = out.get("hooks", {})
    for hook_type in _OUR_HOOK_TYPES:
        entries = hooks.get(hook_type, [])
        filtered = []
        for matcher in entries:
            kept = [h for h in matcher.get("hooks", []) if not _is_our_hook(h)]
            if kept:
                filtered.append({**matcher, "hooks": kept})
        if filtered:
            hooks[hook_type] = filtered
        else:
            hooks.pop(hook_type, None)
    return out


def _render_codex_block(hook_command: str) -> str:
    """Render the TOML snippet we own inside ~/.codex/config.toml.

    Includes `notify` (Codex's async per-turn webhook) and lifecycle
    hooks for the events that map cleanly onto our daemon's notification
    model. PreToolUse fires on every tool call; we let the daemon's
    dedup window handle the noise so each `[[hooks.PreToolUse]]` entry
    here is unconditional (matcher = ".*").
    """
    return (
        f"{_CODEX_BLOCK_START}\n"
        "# Auto-generated by `jarvis-cli install`. Anything between these\n"
        "# markers is replaced on the next install; remove via `jarvis-cli uninstall`.\n"
        "\n"
        f'notify = ["{hook_command}"]\n'
        "\n"
        "[[hooks.PreToolUse]]\n"
        'matcher = ".*"\n'
        "[[hooks.PreToolUse.hooks]]\n"
        'type = "command"\n'
        f'command = "{hook_command}"\n'
        "timeout = 5\n"
        "\n"
        "[[hooks.PermissionRequest]]\n"
        'matcher = ".*"\n'
        "[[hooks.PermissionRequest.hooks]]\n"
        'type = "command"\n'
        f'command = "{hook_command}"\n'
        "timeout = 5\n"
        "\n"
        "[[hooks.UserPromptSubmit]]\n"
        "[[hooks.UserPromptSubmit.hooks]]\n"
        'type = "command"\n'
        f'command = "{hook_command}"\n'
        "timeout = 5\n"
        "\n"
        "[[hooks.PostToolUse]]\n"
        "[[hooks.PostToolUse.hooks]]\n"
        'type = "command"\n'
        f'command = "{hook_command}"\n'
        "timeout = 5\n"
        "\n"
        "[[hooks.PostToolUseFailure]]\n"
        'matcher = ".*"\n'
        "[[hooks.PostToolUseFailure.hooks]]\n"
        'type = "command"\n'
        f'command = "{hook_command}"\n'
        "timeout = 5\n"
        "\n"
        "[[hooks.Stop]]\n"
        "[[hooks.Stop.hooks]]\n"
        'type = "command"\n'
        f'command = "{hook_command}"\n'
        "timeout = 5\n"
        "\n"
        "[[hooks.SessionStart]]\n"
        "[[hooks.SessionStart.hooks]]\n"
        'type = "command"\n'
        f'command = "{hook_command}"\n'
        "timeout = 5\n"
        f"{_CODEX_BLOCK_END}\n"
    )


def merge_codex_config(existing: str, hook_command: str) -> str:
    """Inject (or replace) our managed hook block in a Codex config.toml.

    TOML constrains where bare top-level keys (like `notify`) may appear:
    they must precede any `[section]` header. We therefore insert our
    block *before* the first section header in the user's file, after
    any existing top-level keys. If the block is already present we
    replace it in place. If there are no section headers we append at
    the end.
    """
    block = _render_codex_block(hook_command)
    if _CODEX_BLOCK_RE.search(existing):
        return _CODEX_BLOCK_RE.sub(block, existing)

    lines = existing.splitlines(keepends=True)
    insert_at = None
    for i, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("["):
            insert_at = i
            break
    if insert_at is None:
        # No [section] headers — append (preserve trailing newline)
        sep = "\n" if existing and not existing.endswith("\n") else ""
        return existing + sep + "\n" + block

    # Drop trailing blank lines from the head so we don't accumulate them.
    head = "".join(lines[:insert_at]).rstrip() + "\n\n"
    tail = "".join(lines[insert_at:])
    return head + block + "\n" + tail


def remove_from_codex_config(existing: str) -> str:
    """Strip our managed block from a Codex config.toml; no-op if absent."""
    cleaned = _CODEX_BLOCK_RE.sub("", existing)
    # Collapse the double blank line we may have left behind.
    return re.sub(r"\n{3,}", "\n\n", cleaned)


def render_plist(label: str, program: str, log_dir: str, env: dict[str, str]) -> str:
    """Render a launchd plist for the daemon."""
    env_xml = "\n".join(
        f"        <key>{k}</key>\n        <string>{v}</string>"
        for k, v in env.items()
    )
    return textwrap.dedent(
        f"""\
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>{label}</string>
            <key>ProgramArguments</key>
            <array>
                <string>{program}</string>
            </array>
            <key>RunAtLoad</key>
            <true/>
            <key>KeepAlive</key>
            <true/>
            <key>StandardOutPath</key>
            <string>{log_dir}/daemon.stdout.log</string>
            <key>StandardErrorPath</key>
            <string>{log_dir}/daemon.stderr.log</string>
            <key>EnvironmentVariables</key>
            <dict>
{env_xml}
            </dict>
        </dict>
        </plist>
        """
    )


# --- install wizard --------------------------------------------------------
#
# Goal: a first-time `jarvis-cli install` should leave a working, opinionated
# setup with a one-screen Q&A — no editing config.toml by hand. Existing
# installs keep their config untouched unless the user passes --reconfigure.
# Both paths still patch the CC/Codex hooks and the launchd plist.


_HUMOR_LABELS: tuple[tuple[str, str], ...] = (
    ("deadpan", "Strictly formal — no jokes, no asides."),
    ("light wit", "A hint of dry wit when natural."),
    ("MCU Jarvis", "Banter-prone, occasional wry observation."),
    ("Tony-mode", "Openly sardonic; teases when warranted."),
)

# Wizard profile presets. The keys are stable identifiers used in
# recommendation logic; the values are the (llm_provider, llm_fallback,
# tts_provider, tts_fallback) tuples written into the rendered config.toml.
_PROFILES: dict[str, dict[str, str]] = {
    "local-zero-cost": {
        "label": "Local zero-cost (Ollama + CosyVoice)",
        "llm_provider": "ollama", "llm_fallback": "deepseek",
        "tts_provider": "cosyvoice", "tts_fallback": "say",
    },
    "cloud-cheap": {
        "label": "Cloud-cheap (DeepSeek + ElevenLabs)",
        "llm_provider": "deepseek", "llm_fallback": "ollama",
        "tts_provider": "elevenlabs", "tts_fallback": "say",
    },
    "say-only": {
        "label": "Offline floor (Ollama + macOS `say`)",
        "llm_provider": "ollama", "llm_fallback": "",
        "tts_provider": "say", "tts_fallback": "",
    },
}


@dataclass
class EnvScan:
    """Snapshot of what providers / assets are usable right now."""
    ollama_up: bool = False
    ollama_models: list[str] = field(default_factory=list)
    has_deepseek_key: bool = False
    has_anthropic_key: bool = False
    has_openai_key: bool = False
    has_elevenlabs_key: bool = False
    has_cosyvoice_model: bool = False
    has_xtts_model: bool = False
    has_jarvis_en_voice: bool = False
    has_jarvis_zh_voice: bool = False


def scan_environment(jarvis_dir: Path | None = None) -> EnvScan:
    """Quick non-blocking probe of the operator's setup.

    Pure-by-construction: it doesn't write anything. Used both by the
    wizard (to recommend a profile) and surfaced to the user as a
    one-screen summary at the top of install.
    """
    base = Path(jarvis_dir) if jarvis_dir else Path(JARVIS_DIR)
    scan = EnvScan(
        has_deepseek_key=bool(os.environ.get("DEEPSEEK_API_KEY")),
        has_anthropic_key=bool(os.environ.get("ANTHROPIC_API_KEY")),
        has_openai_key=bool(os.environ.get("OPENAI_API_KEY")),
        has_elevenlabs_key=bool(os.environ.get("ELEVENLABS_API_KEY")),
    )
    cosy_dir = base / "models" / "cosyvoice3-0.5b-candle"
    xtts_dir = base / "models" / "xtts-v2"
    scan.has_cosyvoice_model = cosy_dir.exists() and any(cosy_dir.iterdir()) if cosy_dir.exists() else False
    scan.has_xtts_model = xtts_dir.exists() and any(xtts_dir.iterdir()) if xtts_dir.exists() else False
    scan.has_jarvis_en_voice = (base / "voices" / "jarvis_en.wav").exists()
    scan.has_jarvis_zh_voice = (base / "voices" / "jarvis_zh.wav").exists()
    try:
        r = httpx.get("http://localhost:11434/api/tags", timeout=1.0)
        if r.status_code == 200:
            scan.ollama_up = True
            scan.ollama_models = [m["name"] for m in r.json().get("models", [])]
    except httpx.HTTPError:
        pass
    return scan


def recommend_profile(env: EnvScan) -> str:
    """Pick the most sensible profile for the detected environment.

    Priority: local-zero-cost > cloud-cheap > say-only. Local wins if BOTH
    Ollama is up AND CosyVoice weights are present (the only combo where
    the user pays no per-call cost and gets a high-quality voice). Cloud-
    cheap requires both an LLM key and ElevenLabs. Otherwise fall back to
    the offline floor so the user always gets *something* speakable.
    """
    if env.ollama_up and env.has_cosyvoice_model:
        return "local-zero-cost"
    has_any_cloud_llm = (
        env.has_deepseek_key or env.has_anthropic_key or env.has_openai_key
    )
    if has_any_cloud_llm and env.has_elevenlabs_key:
        return "cloud-cheap"
    return "say-only"


def _print_env_summary(env: EnvScan) -> None:
    def _tick(ok: bool) -> str:
        return "✓" if ok else "✗"

    print("\nEnvironment scan:")
    if env.ollama_up:
        models = ", ".join(env.ollama_models[:5]) if env.ollama_models else "no models pulled"
        print(f"  {_tick(True)} Ollama running ({models})")
    else:
        print(f"  {_tick(False)} Ollama not reachable on localhost:11434")
    keys = [
        ("DEEPSEEK_API_KEY", env.has_deepseek_key),
        ("ANTHROPIC_API_KEY", env.has_anthropic_key),
        ("OPENAI_API_KEY", env.has_openai_key),
        ("ELEVENLABS_API_KEY", env.has_elevenlabs_key),
    ]
    for k, v in keys:
        print(f"  {_tick(v)} {k} {'present' if v else 'missing'}")
    print(f"  {_tick(env.has_cosyvoice_model)} CosyVoice model weights")
    print(f"  {_tick(env.has_xtts_model)} XTTS model weights")
    print(f"  {_tick(env.has_jarvis_en_voice)} reference clip jarvis_en.wav")


# --- interactive prompt helpers --------------------------------------------


def _is_interactive() -> bool:
    """Wizard runs only when both stdin and stdout are TTYs. CI / piped
    invocations get the non-interactive path automatically."""
    return sys.stdin.isatty() and sys.stdout.isatty()


def _prompt_str(question: str, default: str, *, interactive: bool) -> str:
    if not interactive:
        return default
    label = f"{question} [{default}]: " if default else f"{question}: "
    try:
        raw = input(label).strip()
    except EOFError:
        return default
    return raw or default


def _prompt_int_choice(
    question: str,
    labels: list[str],
    default_index: int,
    *,
    interactive: bool,
) -> int:
    """Numeric pick from a small enumerated list. Returns 0-based index."""
    if not interactive:
        return default_index
    print(question)
    for i, lbl in enumerate(labels):
        marker = "*" if i == default_index else " "
        print(f"  {marker} {i}) {lbl}")
    while True:
        try:
            raw = input(f"Pick [{default_index}]: ").strip()
        except EOFError:
            return default_index
        if not raw:
            return default_index
        if raw.isdigit() and 0 <= int(raw) < len(labels):
            return int(raw)
        print(f"  (enter 0–{len(labels) - 1}, or press Enter for default)")


def _prompt_yes_no(question: str, default: bool, *, interactive: bool) -> bool:
    if not interactive:
        return default
    hint = "[Y/n]" if default else "[y/N]"
    try:
        raw = input(f"{question} {hint}: ").strip().lower()
    except EOFError:
        return default
    if not raw:
        return default
    return raw[0] == "y"


# --- wizard ----------------------------------------------------------------


@dataclass
class WizardChoices:
    humor_level: int
    voice_language: str  # "en" | "zh" | "auto"
    city: str            # "" = auto-detect from timezone
    profile: str         # key of _PROFILES


def run_wizard(env: EnvScan, *, existing: dict | None, interactive: bool) -> WizardChoices:
    """Walk the user through humor / language / city / profile.

    `existing` carries the values we'd default to (loaded from the current
    config.toml). On a fresh install, pass None — defaults bake in.
    """
    if existing is None:
        existing = {}

    rec_profile = recommend_profile(env)
    if interactive:
        print(f"\nRecommended profile: {_PROFILES[rec_profile]['label']}")

    # 1) humor level
    cur_humor = int(existing.get("humor_level", 1))
    cur_humor = max(0, min(3, cur_humor))
    humor = _prompt_int_choice(
        "\nHow much wit should Jarvis allow himself?",
        [f"{label} — {desc}" for label, desc in _HUMOR_LABELS],
        default_index=cur_humor,
        interactive=interactive,
    )

    # 2) language
    langs = ["en", "zh", "auto"]
    lang_labels = [
        "English (matches the British voice clone)",
        "Chinese",
        "Auto — pick per event from content",
    ]
    cur_lang = existing.get("voice_language", "en")
    cur_lang_idx = langs.index(cur_lang) if cur_lang in langs else 0
    lang_idx = _prompt_int_choice(
        "\nWhich language should Jarvis speak?",
        lang_labels, default_index=cur_lang_idx, interactive=interactive,
    )

    # 3) city
    cur_city = existing.get("city", "")
    city = _prompt_str(
        "\nDefault city for weather (blank = auto-detect from timezone)",
        default=cur_city, interactive=interactive,
    )

    # 4) profile
    profile_keys = list(_PROFILES)
    profile_labels = [_PROFILES[k]["label"] for k in profile_keys]
    cur_profile = existing.get("profile") or rec_profile
    cur_profile_idx = profile_keys.index(cur_profile) if cur_profile in profile_keys \
        else profile_keys.index(rec_profile)
    profile_idx = _prompt_int_choice(
        "\nWhich provider profile?",
        profile_labels, default_index=cur_profile_idx, interactive=interactive,
    )

    return WizardChoices(
        humor_level=humor,
        voice_language=langs[lang_idx],
        city=city,
        profile=profile_keys[profile_idx],
    )


def _render_configured_toml(choices: WizardChoices, *, preserve: dict | None = None) -> str:
    """Render config.toml from wizard choices, optionally pulling forward
    a handful of cosmetic / tuned values from an existing config so the
    user doesn't lose a hand-set voice_id / ref_text / timesteps."""
    p = preserve or {}
    profile = _PROFILES[choices.profile]
    ref_text_en = p.get("ref_text_en", "")
    el_voice_id = p.get("elevenlabs_voice_id", "")
    n_timesteps = int(p.get("cosyvoice_n_timesteps", 5))
    return textwrap.dedent(f"""\
        # jarvis-cli config.toml — written by `jarvis-cli install` wizard.
        # Re-run with `jarvis-cli install --reconfigure` to walk through again.
        [llm]
        provider = "{profile['llm_provider']}"
        fallback = "{profile['llm_fallback']}"

        [llm.deepseek]
        api_key_env = "DEEPSEEK_API_KEY"
        model = "deepseek-chat"

        [llm.ollama]
        base_url = "http://localhost:11434"
        model = "qwen3:8b"
        timeout_seconds = 30

        [tts]
        provider = "{profile['tts_provider']}"
        fallback = "{profile['tts_fallback']}"

        [tts.cosyvoice]
        model_dir = "~/.jarvis-cli/models/cosyvoice3-0.5b-candle"
        ref_audio_zh = "~/.jarvis-cli/voices/jarvis_zh.wav"
        ref_audio_en = "~/.jarvis-cli/voices/jarvis_en.wav"
        ref_text_en = {json.dumps(ref_text_en, ensure_ascii=False)}
        n_timesteps = {n_timesteps}

        [tts.xtts]
        model_dir = "~/.jarvis-cli/models/xtts-v2"
        ref_audio_zh = "~/.jarvis-cli/voices/jarvis_zh.wav"
        ref_audio_en = "~/.jarvis-cli/voices/jarvis_en.wav"
        device = "mps"

        [tts.elevenlabs]
        api_key_env = "ELEVENLABS_API_KEY"
        voice_id = "{el_voice_id}"
        model = "eleven_turbo_v2_5"

        [behavior]
        dedup_window_seconds = 10
        queue_max_size = 5
        voice_language = "{choices.voice_language}"
        # 0=deadpan, 1=light wit, 2=MCU Jarvis, 3=Tony-mode
        humor_level = {choices.humor_level}
        events = [
            "permission_prompt",
            "idle_prompt",
            "elicitation_dialog",
            "ask_user_question",
            "session_start",
            "tool_failure",
            # "task_complete" fires after every assistant turn — opt in by
            # adding it here to hear a brief "All done, sir."
        ]
        phrase_target_chars = 70
        phrase_hard_cap = 120
        cancel_on_user_action = true

        [behavior.privacy]
        cloud_redaction = true

        [behavior.session_briefing]
        enabled = true
        city = "{choices.city}"
        weather_ttl_seconds = 600
        min_interval_seconds = 0
        weather_timeout_seconds = 3.0
        """)


def _extract_preservable(cfg_path: Path) -> dict:
    """Pull forward a handful of tuned values from an existing config so a
    re-run of the wizard doesn't blow them away. Best-effort — any parse
    failure leaves the dict empty and the wizard falls back to defaults.
    """
    if not cfg_path.exists():
        return {}
    try:
        cfg = load_config(cfg_path)
    except Exception:  # noqa: BLE001 — wizard must never abort on parse drift
        return {}
    return {
        "humor_level": cfg.behavior.humor_level,
        "voice_language": cfg.behavior.voice_language,
        "city": cfg.behavior.session_briefing.city,
        "ref_text_en": cfg.tts.cosyvoice.ref_text_en,
        "elevenlabs_voice_id": cfg.tts.elevenlabs.voice_id,
        "cosyvoice_n_timesteps": cfg.tts.cosyvoice.n_timesteps,
    }


def cmd_install(args: argparse.Namespace) -> int:
    # 1. Make jarvis-cli dir tree
    base = Path(JARVIS_DIR)
    (base / "voices").mkdir(parents=True, exist_ok=True)
    (base / "models").mkdir(parents=True, exist_ok=True)
    (base / "logs").mkdir(parents=True, exist_ok=True)

    # 2. Wizard / config
    cfg_path = Path(DEFAULT_CONFIG_PATH)
    interactive = _is_interactive() and not getattr(args, "non_interactive", False)
    env = scan_environment(base)
    _print_env_summary(env)

    fresh = not cfg_path.exists()
    reconfigure = getattr(args, "reconfigure", False)
    run_the_wizard = fresh or reconfigure

    if run_the_wizard:
        existing = _extract_preservable(cfg_path) if cfg_path.exists() else None
        choices = run_wizard(env, existing=existing, interactive=interactive)
        rendered = _render_configured_toml(
            choices,
            preserve=existing or {},
        )
        if cfg_path.exists():
            backup = cfg_path.with_suffix(cfg_path.suffix + ".bak")
            shutil.copy2(cfg_path, backup)
            print(f"  backed up old config → {backup}")
        cfg_path.write_text(rendered, encoding="utf-8")
        print(f"  wrote {cfg_path} (humor={choices.humor_level}, "
              f"profile={choices.profile})")
    else:
        print(f"  (kept existing {cfg_path}; pass --reconfigure to re-run wizard)")

    # 3. Patch ~/.claude/settings.json
    settings_path = Path(CLAUDE_SETTINGS_PATH)
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    existing = {}
    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            print(f"!! could not parse {settings_path}, refusing to overwrite", file=sys.stderr)
            return 2
    hook_command = shutil.which("jarvis-cli-hook")
    if not hook_command:
        print("!! jarvis-cli-hook not on PATH — did you run `uv sync`?", file=sys.stderr)
        return 4
    merged = merge_claude_settings(existing, hook_command=hook_command)
    settings_path.write_text(json.dumps(merged, indent=2, ensure_ascii=False) + "\n")
    print(f"  patched {settings_path} (hook → {hook_command})")

    # 3b. Patch ~/.codex/config.toml if Codex CLI is on this machine.
    # We detect by file existence rather than `which codex` so a user who
    # has Codex's config dir but a non-PATH binary still gets wired up.
    codex_path = Path(CODEX_CONFIG_PATH)
    if codex_path.exists() or codex_path.parent.exists():
        codex_path.parent.mkdir(parents=True, exist_ok=True)
        existing_codex = codex_path.read_text(encoding="utf-8") if codex_path.exists() else ""
        merged_codex = merge_codex_config(existing_codex, hook_command=hook_command)
        codex_path.write_text(merged_codex, encoding="utf-8")
        print(f"  patched {codex_path} (Codex CLI detected)")
    else:
        print("  (no ~/.codex/ — skipping Codex hook setup)")

    # 4. Write plist
    program = shutil.which("jarvis-cli-daemon")
    if not program:
        print("!! jarvis-cli-daemon not on PATH — did you run `uv sync`?", file=sys.stderr)
        return 3
    plist_path = Path(PLIST_PATH)
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    # Harvest API keys from the operator's current env so launchd can see them
    env = {"PATH": "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"}
    harvest_keys = [
        "DEEPSEEK_API_KEY",
        "ANTHROPIC_API_KEY",
        "OPENAI_API_KEY",
        "ELEVENLABS_API_KEY",
    ]
    for k in harvest_keys:
        v = os.environ.get(k)
        if v:
            env[k] = v
            print(f"  baked {k} into plist")
    # XTTS imports coqui-tts which blocks on a TTY prompt for the CPML
    # license unless COQUI_TOS_AGREED is set. The daemon has no TTY, so
    # without this it would hang on first XTTS synth. CosyVoice doesn't
    # need it but the env var is harmless when unused.
    env["COQUI_TOS_AGREED"] = "1"
    plist_path.write_text(render_plist(PLIST_LABEL, program, str(base / "logs"), env))
    print(f"  wrote {plist_path}")

    # 5. Load plist
    subprocess.run(["launchctl", "unload", str(plist_path)], check=False)
    rc = subprocess.run(["launchctl", "load", str(plist_path)], check=False).returncode
    if rc != 0:
        print(f"!! launchctl load returned {rc}", file=sys.stderr)
        return rc

    print(
        "\nDone. Next steps:\n"
        f"  1. Place reference audio at {base / 'voices/jarvis_zh.wav'} and "
        f"{base / 'voices/jarvis_en.wav'}\n"
        f"  2. If you didn't have DEEPSEEK_API_KEY in your env when you ran install,\n"
        f"     set it now and re-run `jarvis-cli install` (this re-bakes the plist).\n"
        f"  3. Restart Claude Code\n"
        f"  4. Run: jarvis-cli test\n"
    )
    return 0


def cmd_uninstall(args: argparse.Namespace) -> int:
    plist_path = Path(PLIST_PATH)
    if plist_path.exists():
        subprocess.run(["launchctl", "unload", str(plist_path)], check=False)
        plist_path.unlink()
        print(f"  removed {plist_path}")

    settings_path = Path(CLAUDE_SETTINGS_PATH)
    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text())
            pruned = remove_from_claude_settings(existing, hook_command="jarvis-cli-hook")
            settings_path.write_text(json.dumps(pruned, indent=2, ensure_ascii=False) + "\n")
            print(f"  cleaned {settings_path}")
        except json.JSONDecodeError:
            pass

    codex_path = Path(CODEX_CONFIG_PATH)
    if codex_path.exists():
        cleaned = remove_from_codex_config(codex_path.read_text(encoding="utf-8"))
        codex_path.write_text(cleaned, encoding="utf-8")
        print(f"  cleaned {codex_path}")

    if args.purge:
        base = Path(JARVIS_DIR)
        if base.exists():
            shutil.rmtree(base)
            print(f"  purged {base}")
    else:
        print(f"  (kept {JARVIS_DIR}; pass --purge to remove)")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    try:
        r = httpx.get("http://127.0.0.1:9527/health", timeout=1.0)
        print(json.dumps(r.json(), indent=2, ensure_ascii=False))
        return 0
    except httpx.HTTPError as exc:
        print(f"daemon unreachable: {exc}", file=sys.stderr)
        return 1


def cmd_test(args: argparse.Namespace) -> int:
    import socket as _socket

    from .config import load_config

    cfg = load_config(DEFAULT_CONFIG_PATH)
    payload = {
        "notification_type": args.event,
        "tool_name": args.tool,
        "tool_input": {},
        "cwd": os.getcwd(),
        "session_id": "test",
    }
    s = _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM)
    try:
        s.connect(cfg.paths.socket)
        s.sendall((json.dumps(payload) + "\n").encode())
        print(f"sent {args.event} ({args.tool}) to {cfg.paths.socket}")
        return 0
    except OSError as exc:
        print(f"failed: {exc}", file=sys.stderr)
        return 1
    finally:
        s.close()


def cmd_say(args: argparse.Namespace) -> int:
    """Manual one-shot trigger for cases CC doesn't cover (e.g. an assistant
    that wants to alert the user before showing an AskUserQuestion UI).

    Sends a synthetic `idle_prompt` event; `--reason` gets stuffed into
    `tool_name` so the dedup hash is unique per call (no 10s collision) and
    so the LLM has a hint about why it's speaking.
    """
    import socket as _socket
    import uuid

    from .config import load_config

    cfg = load_config(DEFAULT_CONFIG_PATH)
    reason = args.reason or f"manual-{uuid.uuid4().hex[:8]}"
    payload: dict = {
        "notification_type": "idle_prompt",
        "tool_name": reason,
        "tool_input": {},
        "cwd": os.getcwd(),
        "session_id": "manual",
    }
    if args.text:
        payload["text"] = args.text
        payload["lang"] = args.lang
    if args.voice:
        payload["voice_id"] = args.voice
    s = _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM)
    try:
        s.connect(cfg.paths.socket)
        s.sendall((json.dumps(payload) + "\n").encode())
        if args.text:
            print(f"queued say (text={args.text!r}, lang={args.lang})")
        else:
            print(f"queued say (reason={reason!r}, LLM will phrase it)")
        return 0
    except OSError as exc:
        print(f"failed: {exc}", file=sys.stderr)
        return 1
    finally:
        s.close()


def main() -> int:
    parser = argparse.ArgumentParser(prog="jarvis-cli")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_install = sub.add_parser("install")
    p_install.add_argument(
        "--reconfigure", action="store_true",
        help="re-run the setup wizard even when config.toml already exists",
    )
    p_install.add_argument(
        "--non-interactive", action="store_true",
        help="skip all prompts; take defaults (current values when present)",
    )
    p_install.set_defaults(func=cmd_install)
    p_un = sub.add_parser("uninstall")
    p_un.add_argument("--purge", action="store_true", help="also remove ~/.jarvis-cli/")
    p_un.set_defaults(func=cmd_uninstall)
    sub.add_parser("status").set_defaults(func=cmd_status)
    p_test = sub.add_parser("test")
    p_test.add_argument("--event", default="permission_prompt")
    p_test.add_argument("--tool", default="Bash")
    p_test.set_defaults(func=cmd_test)
    p_say = sub.add_parser(
        "say",
        help="manually trigger Jarvis to speak (bypasses dedup; for events CC's "
        "Notification hook doesn't cover, eg AskUserQuestion)",
    )
    p_say.add_argument(
        "--reason",
        default=None,
        help="short label that flows into the LLM prompt as `tool_name`",
    )
    p_say.add_argument(
        "--text",
        default=None,
        help="speak this exact text; skips the LLM entirely",
    )
    p_say.add_argument(
        "--lang",
        default="en",
        choices=["en", "zh"],
        help="language of --text (default: en); ignored without --text",
    )
    p_say.add_argument(
        "--voice",
        default=None,
        help="per-call TTS voice override (eg an ElevenLabs voice_id or a "
        "macOS `say` voice name like Karen); defaults to config",
    )
    p_say.set_defaults(func=cmd_say)

    from .skills.cli import add_subparser as _add_skills_subparser

    _add_skills_subparser(sub)

    from .mcp.cli import add_subparser as _add_mcp_subparser

    _add_mcp_subparser(sub)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
